unit cpl_config;

interface

uses
  fp_gdal;

  {$IFDEF FPC}
  {$PACKRECORDS C}
  {$ENDIF}


const
  GDAL_PREFIX = '/usr';
  SIZEOF_INT = 4;
  SIZEOF_UNSIGNED_LONG = 8;
  SIZEOF_VOIDP = 8;
  SIZEOF_SIZE_T = 8;
  USE_GCC_VISIBILITY_FLAG = 1;
  HAVE_GCC_ATOMIC_BUILTINS = 1;
  HAVE_GCC_BSWAP = 1;
  HAVE_STD_IS_NAN = 1;

  SIZEOF_LONG_INT = 8;
  CPL_MULTIPROC_PTHREAD = 1;
  HAVE_PTHREAD_MUTEX_RECURSIVE = 1;
  HAVE_PTHREAD_MUTEX_ADAPTIVE_NP = 1;
  HAVE_PTHREAD_SPIN_LOCK = 1;
  HAVE_PTHREAD_ATFORK = 1;
  HAVE_5ARGS_MREMAP = 1;
  HAVE_SYS_RANDOM_H = 1;
  HAVE_GETRANDOM = 1;
  HAVE_GETRLIMIT = 1;
  HAVE_RLIMIT_AS = 1;
  HAVE_DLFCN_H = 1;
  HAVE_FCNTL_H = 1;
  HAVE_GETCWD = 1;
  HAVE_ICONV = 1;
  HAVE_UINT128_T = 1;
  HAVE_LOCALE_H = 1;
  HAVE_SYS_STAT_H = 1;
  HAVE_SYS_TYPES_H = 1;
  HAVE_UNISTD_H = 1;
  HAVE_VSNPRINTF = 1;
  HAVE_READLINK = 1;
  HAVE_POSIX_SPAWNP = 1;
  HAVE_POSIX_MEMALIGN = 1;
  HAVE_VFORK = 1;
  HAVE_MMAP = 1;
  HAVE_SIGACTION = 1;
  HAVE_STATVFS = 1;
  HAVE_STATVFS64 = 1;
  HAVE_LSTAT = 1;
  UNIX_STDIO_64 = 1;
  HAVE_SC_PHYS_PAGES = 1;
  HAVE_SCHED_GETAFFINITY = 1;
  HAVE_USELOCALE = 1;

const
  DONT_DEPRECATE_SPRINTF = 0;

const
  HAVE_GCC_WARNING_ZERO_AS_NULL_POINTER_CONSTANT = 1;
  HAVE_CTIME_R = 1;
  HAVE_LOCALTIME_R = 1;
  HAVE_GMTIME_R = 1;

  // === Konventiert am: 2-10-26 15:57:25 ===


implementation



end.
