unit atspi_constants;

interface

uses
  fp_glib2, fp_atspi;

  {$IFDEF FPC}
  {$PACKRECORDS C}
  {$ENDIF}


type
  PAtspiLocaleType = ^TAtspiLocaleType;
  TAtspiLocaleType = longint;
const
  ATSPI_LOCALE_TYPE_MESSAGES = 0;
  ATSPI_LOCALE_TYPE_COLLATE = 1;
  ATSPI_LOCALE_TYPE_CTYPE = 2;
  ATSPI_LOCALE_TYPE_MONETARY = 3;
  ATSPI_LOCALE_TYPE_NUMERIC = 4;
  ATSPI_LOCALE_TYPE_TIME = 5;
  ATSPI_LOCALE_TYPE_COUNT = 5 + 1;

type
  PAtspiCoordType = ^TAtspiCoordType;
  TAtspiCoordType = longint;
const
  ATSPI_COORD_TYPE_SCREEN = 0;
  ATSPI_COORD_TYPE_WINDOW = 1;
  ATSPI_COORD_TYPE_PARENT = 2;
  ATSPI_COORD_TYPE_COUNT = 2 + 1;

type
  PAtspiCollectionSortOrder = ^TAtspiCollectionSortOrder;
  TAtspiCollectionSortOrder = longint;
const
  ATSPI_Collection_SORT_ORDER_INVALID = 0;
  ATSPI_Collection_SORT_ORDER_CANONICAL = 1;
  ATSPI_Collection_SORT_ORDER_FLOW = 2;
  ATSPI_Collection_SORT_ORDER_TAB = 3;
  ATSPI_Collection_SORT_ORDER_REVERSE_CANONICAL = 4;
  ATSPI_Collection_SORT_ORDER_REVERSE_FLOW = 5;
  ATSPI_Collection_SORT_ORDER_REVERSE_TAB = 6;
  ATSPI_Collection_SORT_ORDER_LAST_DEFINED = 7;
  ATSPI_SORTORDER_COUNT = 7 + 1;

type
  PAtspiCollectionMatchType = ^TAtspiCollectionMatchType;
  TAtspiCollectionMatchType = longint;
const
  ATSPI_Collection_MATCH_INVALID = 0;
  ATSPI_Collection_MATCH_ALL = 1;
  ATSPI_Collection_MATCH_ANY = 2;
  ATSPI_Collection_MATCH_NONE = 3;
  ATSPI_Collection_MATCH_EMPTY = 4;
  ATSPI_Collection_MATCH_LAST_DEFINED = 5;
  ATSPI_MATCHTYPES_COUNT = 5 + 1;

type
  PAtspiCollectionTreeTraversalType = ^TAtspiCollectionTreeTraversalType;
  TAtspiCollectionTreeTraversalType = longint;
const
  ATSPI_Collection_TREE_RESTRICT_CHILDREN = 0;
  ATSPI_Collection_TREE_RESTRICT_SIBLING = 1;
  ATSPI_Collection_TREE_INORDER = 2;
  ATSPI_Collection_TREE_LAST_DEFINED = 3;
  ATSPI_TREETRAVERSALTYPE_COUNT = 3 + 1;

type
  PAtspiComponentLayer = ^TAtspiComponentLayer;
  TAtspiComponentLayer = longint;
const
  ATSPI_LAYER_INVALID = 0;
  ATSPI_LAYER_BACKGROUND = 1;
  ATSPI_LAYER_CANVAS = 2;
  ATSPI_LAYER_WIDGET = 3;
  ATSPI_LAYER_MDI = 4;
  ATSPI_LAYER_POPUP = 5;
  ATSPI_LAYER_OVERLAY = 6;
  ATSPI_LAYER_WINDOW = 7;
  ATSPI_LAYER_LAST_DEFINED = 8;
  ATSPI_COMPONENTLAYER_COUNT = 8 + 1;

type
  PAtspiTextBoundaryType = ^TAtspiTextBoundaryType;
  TAtspiTextBoundaryType = longint;
const
  ATSPI_TEXT_BOUNDARY_CHAR = 0;
  ATSPI_TEXT_BOUNDARY_WORD_START = 1;
  ATSPI_TEXT_BOUNDARY_WORD_END = 2;
  ATSPI_TEXT_BOUNDARY_SENTENCE_START = 3;
  ATSPI_TEXT_BOUNDARY_SENTENCE_END = 4;
  ATSPI_TEXT_BOUNDARY_LINE_START = 5;
  ATSPI_TEXT_BOUNDARY_LINE_END = 6;

type
  PAtspiTextGranularity = ^TAtspiTextGranularity;
  TAtspiTextGranularity = longint;
const
  ATSPI_TEXT_GRANULARITY_CHAR = 0;
  ATSPI_TEXT_GRANULARITY_WORD = 1;
  ATSPI_TEXT_GRANULARITY_SENTENCE = 2;
  ATSPI_TEXT_GRANULARITY_LINE = 3;
  ATSPI_TEXT_GRANULARITY_PARAGRAPH = 4;
  ATSPI_TEXT_BOUNDARY_TYPE_COUNT = 6 + 1;

type
  PAtspiTextClipType = ^TAtspiTextClipType;
  TAtspiTextClipType = longint;
const
  ATSPI_TEXT_CLIP_NONE = 0;
  ATSPI_TEXT_CLIP_MIN = 1;
  ATSPI_TEXT_CLIP_MAX = 2;
  ATSPI_TEXT_CLIP_BOTH = 3;
  ATSPI_TEXT_CLIP_TYPE_COUNT = 3 + 1;

type
  PAtspiStateType = ^TAtspiStateType;
  TAtspiStateType = longint;
const
  ATSPI_STATE_INVALID = 0;
  ATSPI_STATE_ACTIVE = 1;
  ATSPI_STATE_ARMED = 2;
  ATSPI_STATE_BUSY = 3;
  ATSPI_STATE_CHECKED = 4;
  ATSPI_STATE_COLLAPSED = 5;
  ATSPI_STATE_DEFUNCT = 6;
  ATSPI_STATE_EDITABLE = 7;
  ATSPI_STATE_ENABLED = 8;
  ATSPI_STATE_EXPANDABLE = 9;
  ATSPI_STATE_EXPANDED = 10;
  ATSPI_STATE_FOCUSABLE = 11;
  ATSPI_STATE_FOCUSED = 12;
  ATSPI_STATE_HAS_TOOLTIP = 13;
  ATSPI_STATE_HORIZONTAL = 14;
  ATSPI_STATE_ICONIFIED = 15;
  ATSPI_STATE_MODAL = 16;
  ATSPI_STATE_MULTI_LINE = 17;
  ATSPI_STATE_MULTISELECTABLE = 18;
  ATSPI_STATE_OPAQUE = 19;
  ATSPI_STATE_PRESSED = 20;
  ATSPI_STATE_RESIZABLE = 21;
  ATSPI_STATE_SELECTABLE = 22;
  ATSPI_STATE_SELECTED = 23;
  ATSPI_STATE_SENSITIVE = 24;
  ATSPI_STATE_SHOWING = 25;
  ATSPI_STATE_SINGLE_LINE = 26;
  ATSPI_STATE_STALE = 27;
  ATSPI_STATE_TRANSIENT = 28;
  ATSPI_STATE_VERTICAL = 29;
  ATSPI_STATE_VISIBLE = 30;
  ATSPI_STATE_MANAGES_DESCENDANTS = 31;
  ATSPI_STATE_INDETERMINATE = 32;
  ATSPI_STATE_REQUIRED = 33;
  ATSPI_STATE_TRUNCATED = 34;
  ATSPI_STATE_ANIMATED = 35;
  ATSPI_STATE_INVALID_ENTRY = 36;
  ATSPI_STATE_SUPPORTS_AUTOCOMPLETION = 37;
  ATSPI_STATE_SELECTABLE_TEXT = 38;
  ATSPI_STATE_IS_DEFAULT = 39;
  ATSPI_STATE_VISITED = 40;
  ATSPI_STATE_CHECKABLE = 41;
  ATSPI_STATE_HAS_POPUP = 42;
  ATSPI_STATE_READ_ONLY = 43;
  ATSPI_STATE_LAST_DEFINED = 44;
  ATSPI_STATETYPE_COUNT = 41 + 1;

type
  PAtspiKeyEventType = ^TAtspiKeyEventType;
  TAtspiKeyEventType = longint;
const
  ATSPI_KEY_PRESSED = 0;
  ATSPI_KEY_RELEASED = 1;
  ATSPI_KEYEVENTTYPE_COUNT = 1 + 1;

type
  PAtspiEventType = ^TAtspiEventType;
  TAtspiEventType = longint;
const
  ATSPI_KEY_PRESSED_EVENT = 0;
  ATSPI_KEY_RELEASED_EVENT = 1;
  ATSPI_BUTTON_PRESSED_EVENT = 2;
  ATSPI_BUTTON_RELEASED_EVENT = 3;
  ATSPI_EVENTTYPE_COUNT = 3 + 1;

type
  PAtspiKeySynthType = ^TAtspiKeySynthType;
  TAtspiKeySynthType = longint;
const
  ATSPI_KEY_PRESS = 0;
  ATSPI_KEY_RELEASE = 1;
  ATSPI_KEY_PRESSRELEASE = 2;
  ATSPI_KEY_SYM = 3;
  ATSPI_KEY_STRING = 4;
  ATSPI_KEY_LOCKMODIFIERS = 5;
  ATSPI_KEY_UNLOCKMODIFIERS = 6;
  ATSPI_KEYSYNTHTYPE_COUNT = 4 + 1;

type
  PAtspiModifierType = ^TAtspiModifierType;
  TAtspiModifierType = longint;
const
  ATSPI_MODIFIER_SHIFT = 0;
  ATSPI_MODIFIER_SHIFTLOCK = 1;
  ATSPI_MODIFIER_CONTROL = 2;
  ATSPI_MODIFIER_ALT = 3;
  ATSPI_MODIFIER_META = 4;
  ATSPI_MODIFIER_META2 = 5;
  ATSPI_MODIFIER_META3 = 6;
  ATSPI_MODIFIER_NUMLOCK = 14;
  ATSPI_MODIFIERTYPE_COUNT = 7 + 1;

type
  PAtspiRelationType = ^TAtspiRelationType;
  TAtspiRelationType = longint;
const
  ATSPI_RELATION_NULL = 0;
  ATSPI_RELATION_LABEL_FOR = 1;
  ATSPI_RELATION_LABELLED_BY = 2;
  ATSPI_RELATION_CONTROLLER_FOR = 3;
  ATSPI_RELATION_CONTROLLED_BY = 4;
  ATSPI_RELATION_MEMBER_OF = 5;
  ATSPI_RELATION_TOOLTIP_FOR = 6;
  ATSPI_RELATION_NODE_CHILD_OF = 7;
  ATSPI_RELATION_NODE_PARENT_OF = 8;
  ATSPI_RELATION_EXTENDED = 9;
  ATSPI_RELATION_FLOWS_TO = 10;
  ATSPI_RELATION_FLOWS_FROM = 11;
  ATSPI_RELATION_SUBWINDOW_OF = 12;
  ATSPI_RELATION_EMBEDS = 13;
  ATSPI_RELATION_EMBEDDED_BY = 14;
  ATSPI_RELATION_POPUP_FOR = 15;
  ATSPI_RELATION_PARENT_WINDOW_OF = 16;
  ATSPI_RELATION_DESCRIPTION_FOR = 17;
  ATSPI_RELATION_DESCRIBED_BY = 18;
  ATSPI_RELATION_DETAILS = 19;
  ATSPI_RELATION_DETAILS_FOR = 20;
  ATSPI_RELATION_ERROR_MESSAGE = 21;
  ATSPI_RELATION_ERROR_FOR = 22;
  ATSPI_RELATION_LAST_DEFINED = 23;
  ATSPI_RELATIONTYPE_COUNT = 23 + 1;

type
  PAtspiRole = ^TAtspiRole;
  TAtspiRole = longint;
const
  ATSPI_ROLE_INVALID = 0;
  ATSPI_ROLE_ACCELERATOR_LABEL = 1;
  ATSPI_ROLE_ALERT = 2;
  ATSPI_ROLE_ANIMATION = 3;
  ATSPI_ROLE_ARROW = 4;
  ATSPI_ROLE_CALENDAR = 5;
  ATSPI_ROLE_CANVAS = 6;
  ATSPI_ROLE_CHECK_BOX = 7;
  ATSPI_ROLE_CHECK_MENU_ITEM = 8;
  ATSPI_ROLE_COLOR_CHOOSER = 9;
  ATSPI_ROLE_COLUMN_HEADER = 10;
  ATSPI_ROLE_COMBO_BOX = 11;
  ATSPI_ROLE_DATE_EDITOR = 12;
  ATSPI_ROLE_DESKTOP_ICON = 13;
  ATSPI_ROLE_DESKTOP_FRAME = 14;
  ATSPI_ROLE_DIAL = 15;
  ATSPI_ROLE_DIALOG = 16;
  ATSPI_ROLE_DIRECTORY_PANE = 17;
  ATSPI_ROLE_DRAWING_AREA = 18;
  ATSPI_ROLE_FILE_CHOOSER = 19;
  ATSPI_ROLE_FILLER = 20;
  ATSPI_ROLE_FOCUS_TRAVERSABLE = 21;
  ATSPI_ROLE_FONT_CHOOSER = 22;
  ATSPI_ROLE_FRAME = 23;
  ATSPI_ROLE_GLASS_PANE = 24;
  ATSPI_ROLE_HTML_CONTAINER = 25;
  ATSPI_ROLE_ICON = 26;
  ATSPI_ROLE_IMAGE = 27;
  ATSPI_ROLE_INTERNAL_FRAME = 28;
  ATSPI_ROLE_LABEL = 29;
  ATSPI_ROLE_LAYERED_PANE = 30;
  ATSPI_ROLE_LIST = 31;
  ATSPI_ROLE_LIST_ITEM = 32;
  ATSPI_ROLE_MENU = 33;
  ATSPI_ROLE_MENU_BAR = 34;
  ATSPI_ROLE_MENU_ITEM = 35;
  ATSPI_ROLE_OPTION_PANE = 36;
  ATSPI_ROLE_PAGE_TAB = 37;
  ATSPI_ROLE_PAGE_TAB_LIST = 38;
  ATSPI_ROLE_PANEL = 39;
  ATSPI_ROLE_PASSWORD_TEXT = 40;
  ATSPI_ROLE_POPUP_MENU = 41;
  ATSPI_ROLE_PROGRESS_BAR = 42;
  ATSPI_ROLE_PUSH_BUTTON = 43;
  ATSPI_ROLE_RADIO_BUTTON = 44;
  ATSPI_ROLE_RADIO_MENU_ITEM = 45;
  ATSPI_ROLE_ROOT_PANE = 46;
  ATSPI_ROLE_ROW_HEADER = 47;
  ATSPI_ROLE_SCROLL_BAR = 48;
  ATSPI_ROLE_SCROLL_PANE = 49;
  ATSPI_ROLE_SEPARATOR = 50;
  ATSPI_ROLE_SLIDER = 51;
  ATSPI_ROLE_SPIN_BUTTON = 52;
  ATSPI_ROLE_SPLIT_PANE = 53;
  ATSPI_ROLE_STATUS_BAR = 54;
  ATSPI_ROLE_TABLE = 55;
  ATSPI_ROLE_TABLE_CELL = 56;
  ATSPI_ROLE_TABLE_COLUMN_HEADER = 57;
  ATSPI_ROLE_TABLE_ROW_HEADER = 58;
  ATSPI_ROLE_TEAROFF_MENU_ITEM = 59;
  ATSPI_ROLE_TERMINAL = 60;
  ATSPI_ROLE_TEXT = 61;
  ATSPI_ROLE_TOGGLE_BUTTON = 62;
  ATSPI_ROLE_TOOL_BAR = 63;
  ATSPI_ROLE_TOOL_TIP = 64;
  ATSPI_ROLE_TREE = 65;
  ATSPI_ROLE_TREE_TABLE = 66;
  ATSPI_ROLE_UNKNOWN = 67;
  ATSPI_ROLE_VIEWPORT = 68;
  ATSPI_ROLE_WINDOW = 69;
  ATSPI_ROLE_EXTENDED = 70;
  ATSPI_ROLE_HEADER = 71;
  ATSPI_ROLE_FOOTER = 72;
  ATSPI_ROLE_PARAGRAPH = 73;
  ATSPI_ROLE_RULER = 74;
  ATSPI_ROLE_APPLICATION = 75;
  ATSPI_ROLE_AUTOCOMPLETE = 76;
  ATSPI_ROLE_EDITBAR = 77;
  ATSPI_ROLE_EMBEDDED = 78;
  ATSPI_ROLE_ENTRY = 79;
  ATSPI_ROLE_CHART = 80;
  ATSPI_ROLE_CAPTION = 81;
  ATSPI_ROLE_DOCUMENT_FRAME = 82;
  ATSPI_ROLE_HEADING = 83;
  ATSPI_ROLE_PAGE = 84;
  ATSPI_ROLE_SECTION = 85;
  ATSPI_ROLE_REDUNDANT_OBJECT = 86;
  ATSPI_ROLE_FORM = 87;
  ATSPI_ROLE_LINK = 88;
  ATSPI_ROLE_INPUT_METHOD_WINDOW = 89;
  ATSPI_ROLE_TABLE_ROW = 90;
  ATSPI_ROLE_TREE_ITEM = 91;
  ATSPI_ROLE_DOCUMENT_SPREADSHEET = 92;
  ATSPI_ROLE_DOCUMENT_PRESENTATION = 93;
  ATSPI_ROLE_DOCUMENT_TEXT = 94;
  ATSPI_ROLE_DOCUMENT_WEB = 95;
  ATSPI_ROLE_DOCUMENT_EMAIL = 96;
  ATSPI_ROLE_COMMENT = 97;
  ATSPI_ROLE_LIST_BOX = 98;
  ATSPI_ROLE_GROUPING = 99;
  ATSPI_ROLE_IMAGE_MAP = 100;
  ATSPI_ROLE_NOTIFICATION = 101;
  ATSPI_ROLE_INFO_BAR = 102;
  ATSPI_ROLE_LEVEL_BAR = 103;
  ATSPI_ROLE_TITLE_BAR = 104;
  ATSPI_ROLE_BLOCK_QUOTE = 105;
  ATSPI_ROLE_AUDIO = 106;
  ATSPI_ROLE_VIDEO = 107;
  ATSPI_ROLE_DEFINITION = 108;
  ATSPI_ROLE_ARTICLE = 109;
  ATSPI_ROLE_LANDMARK = 110;
  ATSPI_ROLE_LOG = 111;
  ATSPI_ROLE_MARQUEE = 112;
  ATSPI_ROLE_MATH = 113;
  ATSPI_ROLE_RATING = 114;
  ATSPI_ROLE_TIMER = 115;
  ATSPI_ROLE_STATIC = 116;
  ATSPI_ROLE_MATH_FRACTION = 117;
  ATSPI_ROLE_MATH_ROOT = 118;
  ATSPI_ROLE_SUBSCRIPT = 119;
  ATSPI_ROLE_SUPERSCRIPT = 120;
  ATSPI_ROLE_DESCRIPTION_LIST = 121;
  ATSPI_ROLE_DESCRIPTION_TERM = 122;
  ATSPI_ROLE_DESCRIPTION_VALUE = 123;
  ATSPI_ROLE_FOOTNOTE = 124;
  ATSPI_ROLE_CONTENT_DELETION = 125;
  ATSPI_ROLE_CONTENT_INSERTION = 126;
  ATSPI_ROLE_MARK = 127;
  ATSPI_ROLE_SUGGESTION = 128;
  ATSPI_ROLE_PUSH_BUTTON_MENU = 129;
  ATSPI_ROLE_LAST_DEFINED = 130;
  ATSPI_ROLE_COUNT = 130 + 1;

type
  PAtspiCache = ^TAtspiCache;
  TAtspiCache = longint;
const
  ATSPI_CACHE_NONE = 0;
  ATSPI_CACHE_PARENT = 1 shl 0;
  ATSPI_CACHE_CHILDREN = 1 shl 1;
  ATSPI_CACHE_NAME = 1 shl 2;
  ATSPI_CACHE_DESCRIPTION = 1 shl 3;
  ATSPI_CACHE_STATES = 1 shl 4;
  ATSPI_CACHE_ROLE = 1 shl 5;
  ATSPI_CACHE_INTERFACES = 1 shl 6;
  ATSPI_CACHE_ATTRIBUTES = 1 shl 7;
  ATSPI_CACHE_ALL = $3fffffff;
  ATSPI_CACHE_DEFAULT = (((((ATSPI_CACHE_PARENT or ATSPI_CACHE_CHILDREN) or ATSPI_CACHE_NAME) or ATSPI_CACHE_DESCRIPTION) or ATSPI_CACHE_STATES) or ATSPI_CACHE_ROLE) or ATSPI_CACHE_INTERFACES;
  ATSPI_CACHE_UNDEFINED = $40000000;

type
  PAtspiScrollType = ^TAtspiScrollType;
  TAtspiScrollType = longint;
const
  ATSPI_SCROLL_TOP_LEFT = 0;
  ATSPI_SCROLL_BOTTOM_RIGHT = 1;
  ATSPI_SCROLL_TOP_EDGE = 2;
  ATSPI_SCROLL_BOTTOM_EDGE = 3;
  ATSPI_SCROLL_LEFT_EDGE = 4;
  ATSPI_SCROLL_RIGHT_EDGE = 5;
  ATSPI_SCROLL_ANYWHERE = 6;
  ATSPI_SCROLLTYPE_COUNT = 6 + 1;

type
  PAtspiLive = ^TAtspiLive;
  TAtspiLive = longint;
const
  ATSPI_LIVE_NONE = 0;
  ATSPI_LIVE_POLITE = 1;
  ATSPI_LIVE_ASSERTIVE = 2;

const
  ATSPI_DBUS_NAME_REGISTRY = 'org.a11y.atspi.Registry';
  ATSPI_DBUS_PATH_REGISTRY = '/org/a11y/atspi/registry';
  ATSPI_DBUS_INTERFACE_REGISTRY = 'org.a11y.atspi.Registry';
  ATSPI_DBUS_PATH_NULL = '/org/a11y/atspi/null';
  ATSPI_DBUS_PATH_ROOT = '/org/a11y/atspi/accessible/root';
  ATSPI_DBUS_PATH_DEC = '/org/a11y/atspi/registry/deviceeventcontroller';
  ATSPI_DBUS_INTERFACE_DEC = 'org.a11y.atspi.DeviceEventController';
  ATSPI_DBUS_INTERFACE_DEVICE_EVENT_LISTENER = 'org.a11y.atspi.DeviceEventListener';
  ATSPI_DBUS_INTERFACE_CACHE = 'org.a11y.atspi.Cache';
  ATSPI_DBUS_INTERFACE_ACCESSIBLE = 'org.a11y.atspi.Accessible';
  ATSPI_DBUS_INTERFACE_ACTION = 'org.a11y.atspi.Action';
  ATSPI_DBUS_INTERFACE_APPLICATION = 'org.a11y.atspi.Application';
  ATSPI_DBUS_INTERFACE_COLLECTION = 'org.a11y.atspi.Collection';
  ATSPI_DBUS_INTERFACE_COMPONENT = 'org.a11y.atspi.Component';
  ATSPI_DBUS_INTERFACE_DOCUMENT = 'org.a11y.atspi.Document';
  ATSPI_DBUS_INTERFACE_EDITABLE_TEXT = 'org.a11y.atspi.EditableText';
  ATSPI_DBUS_INTERFACE_EVENT_KEYBOARD = 'org.a11y.atspi.Event.Keyboard';
  ATSPI_DBUS_INTERFACE_EVENT_MOUSE = 'org.a11y.atspi.Event.Mouse';
  ATSPI_DBUS_INTERFACE_EVENT_OBJECT = 'org.a11y.atspi.Event.Object';
  ATSPI_DBUS_INTERFACE_HYPERLINK = 'org.a11y.atspi.Hyperlink';
  ATSPI_DBUS_INTERFACE_HYPERTEXT = 'org.a11y.atspi.Hypertext';
  ATSPI_DBUS_INTERFACE_IMAGE = 'org.a11y.atspi.Image';
  ATSPI_DBUS_INTERFACE_SELECTION = 'org.a11y.atspi.Selection';
  ATSPI_DBUS_INTERFACE_TABLE = 'org.a11y.atspi.Table';
  ATSPI_DBUS_INTERFACE_TABLE_CELL = 'org.a11y.atspi.TableCell';
  ATSPI_DBUS_INTERFACE_TEXT = 'org.a11y.atspi.Text';
  ATSPI_DBUS_INTERFACE_VALUE = 'org.a11y.atspi.Value';
  ATSPI_DBUS_INTERFACE_SOCKET = 'org.a11y.atspi.Socket';
  ATSPI_DBUS_PATH_SCREEN_READER = '/org/a11y/atspi/screenreader';
  ATSPI_DBUS_INTERFACE_EVENT_SCREEN_READER = 'org.a11y.atspi.Event.ScreenReader';

  // === Konventiert am: 26-9-26 12:52:42 ===


implementation



end.
