

{$include atspi/atspi_version.inc}
{$include atspi/atspi_constants.inc}
{$include atspi/atspi_enum_types.inc}
{$include atspi/atspi_application.inc}
{$include atspi/atspi_object.inc}
{$include atspi/atspi_types.inc}
{$include atspi/atspi_action.inc}
{$include atspi/atspi_stateset.inc}
{$include atspi/atspi_matchrule.inc}
{$include atspi/atspi_collection.inc}
{$include atspi/atspi_component.inc}
{$include atspi/atspi_device.inc}
{$include atspi/atspi_device_legacy.inc}
{$include atspi/atspi_device_listener.inc}
{$include atspi/atspi_device_x11.inc}
{$include atspi/atspi_document.inc}
{$include atspi/atspi_editabletext.inc}
{$include atspi/atspi_event_listener.inc}
{$include atspi/atspi_gmain.inc}
{$include atspi/atspi_text.inc}
{$include atspi/atspi_hyperlink.inc}
{$include atspi/atspi_hypertext.inc}
{$include atspi/atspi_image.inc}
{$include atspi/atspi_misc.inc}
{$include atspi/atspi_registry.inc}
{$include atspi/atspi_relation.inc}
{$include atspi/atspi_selection.inc}
{$include atspi/atspi_table.inc}
{$include atspi/atspi_table_cell.inc}
{$include atspi/atspi_value.inc}
{$include atspi/atspi_accessible.inc}

