

{$include llvm/Types.inc}
{$include llvm/Analysis.inc}
{$include llvm/BitReader.inc}
{$include llvm/BitWriter.inc}
{$include llvm/blake3.inc}
{$include llvm/Comdat.inc}
{$include llvm/Core.inc}
{$include llvm/DataTypes.inc}
{$include llvm/DebugInfo.inc}
{$include llvm/DisassemblerTypes.inc}
{$include llvm/Disassembler.inc}
{$include llvm/ErrorHandling.inc}
{$include llvm/Error.inc}
{$include llvm/Target.inc}
{$include llvm/TargetMachine.inc}
{$include llvm/ExecutionEngine.inc}
{$include llvm/IRReader.inc}
{$include llvm/Linker.inc}
{$include llvm/Orc.inc}
{$include llvm/OrcEE.inc}
{$include llvm/LLJIT.inc}
{$include llvm/LLJITUtils.inc}
{$include llvm/lto.inc}
{$include llvm/Object.inc}
{$include llvm/Remarks.inc}
{$include llvm/Support.inc}

{$include llvm/Transforms/PassBuilder.inc}

