

{$IFDEF read_function}
procedure atspi_dbus_connection_setup_with_g_main(connection: PDBusConnection; context: PGMainContext); cdecl; external libatspi;
procedure atspi_dbus_server_setup_with_g_main(server: PDBusServer; context: PGMainContext); cdecl; external libatspi;
{$ENDIF read_function}

// === Konventiert am: 26-9-26 13:07:56 ===



{$IFDEF read_implementation}



{$ENDIF read_implementation}
